**STEP 1: GETTING DATASET**


**STEP 2: IMPORTING LIBRARIES**

In [1]:
import pandas as pd

In [2]:
import numpy as np

------------X--------------

**STEP 3: IMPORTING DATASET**

In [3]:
dataset=pd.read_csv('Data_Preprocessing.csv')

In [4]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

--------------X------------------

*Seprating the Independent data and Dependent data and putting them into an array:*

In [5]:
x=dataset[['Country','Age','Salary']].values

In [6]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
y=dataset[['Purchased']]

In [8]:
y


Purchased
0        No
1       Yes
2        No
3        No
4       Yes
5       Yes
6        No
7       Yes
8        No
9       Yes

*To make this Independent dataset (y) an array we use .values:*

In [9]:
y=dataset[['Purchased']].values

In [10]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

-------------X-------------------

**STEP 4: FINDING MISSING VALUES**

*Importing Library to find out the missing data using mean, median, or mode:*

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
imputer=SimpleImputer(
    missing_values=np.nan,strategy='mean')

*The below line means we are selecting all the rows(:) of the columns 1 to 3 i.e. from AGE to SALARY:*

In [13]:
imputer=imputer.fit(x[:,1:3])

*The below line means we are transforming the nan values by the mean:*

In [14]:
x[:,1:3]=imputer.transform(x[:,1:3])

In [15]:
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

-------------------x------------------------

**STEP 5: ENCODING CATEGORIAL DATA**

*We do this step because most of the Algorithms dont work on Categorial data and they need Numeric data. Except: Decision Tree Algorithm.*

*We are using OneHotEncoder for the Country names column:*

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
onehotencoder=OneHotEncoder()

In [18]:
x=onehotencoder.fit_transform(dataset.Country.values.reshape(-1,1)).toarray()

*The below result is called DUMMY ENCODING:*

In [19]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

*We use LabelEncoder for Purchased column:*

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
labelencoder_y=LabelEncoder()

In [22]:
y=labelencoder_y.fit_transform(y)

C:\Users\KIIT\New folder\Lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [23]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

------------------X------------------------

**STEP 6: SPLITTING OF DATASET INTO TRAINING AND TEST SET**

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_train

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [28]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

In [29]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [30]:
y_test

array([0, 0])

--------------X----------------

**STEP 7: FEATURE SCALING**

In [31]:
from sklearn.preprocessing import StandardScaler

In [32]:
sc_x=StandardScaler()

In [34]:
x_train=sc_x.fit_transform(x_train)

In [35]:
x_test=sc_x.transform(x_test)

In [36]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [37]:
x_test

array([[-1.        ,  2.64575131, -0.77459667],
       [-1.        ,  2.64575131, -0.77459667]])

---------------X---------------